### ISSUE TITLE
How to use it with taskwarrior

### ISSUE THREAD

**Issue by vonpupp** [coddingtonbear/timebook#7]
Hello,

I am trying to understand how the `t taskwarrior` command works. I currently have one task on taskwarrior and I started it, however after issuing the `t taskwarrior` I get the following error:

```
> $ t taskwarrior                                                              
Watching taskwarrior output...
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/timebook-3.7.5-py2.7.egg/timebook/commands.py", line 148, in run_command
    commands[func](db, args)
  File "/usr/lib/python2.7/site-packages/timebook-3.7.5-py2.7.egg/timebook/commands.py", line 107, in decorated
    res = func(db, args, **kwargs)
  File "/usr/lib/python2.7/site-packages/timebook-3.7.5-py2.7.egg/timebook/commands.py", line 312, in taskwarrior
    tasks, task_hash = poll_taskwarrior()
  File "/usr/lib/python2.7/site-packages/timebook-3.7.5-py2.7.egg/timebook/commands.py", line 302, in poll_taskwarrior
    json.loads(line.rstrip(','))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/bin/t", line 11, in <module>
    load_entry_point('timebook==3.7.5', 'console_scripts', 't')()
  File "/usr/lib/python2.7/site-packages/timebook-3.7.5-py2.7.egg/timebook/cmdline.py", line 86, in run_from_cmdline
    run_command(db, cmd, args)
  File "/usr/lib/python2.7/site-packages/timebook-3.7.5-py2.7.egg/timebook/commands.py", line 148, in run_command
    commands[func](db, args)
  File "/usr/lib/python2.7/site-packages/timebook-3.7.5-py2.7.egg/timebook/commands.py", line 107, in decorated
    res = func(db, args, **kwargs)
  File "/usr/lib/python2.7/site-packages/timebook-3.7.5-py2.7.egg/timebook/commands.py", line 312, in taskwarrior
    tasks, task_hash = poll_taskwarrior()
  File "/usr/lib/python2.7/site-packages/timebook-3.7.5-py2.7.egg/timebook/commands.py", line 302, in poll_taskwarrior
    json.loads(line.rstrip(','))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 1 (char 0)
```

Could you please explain the workflow that I should use to get a timesheet built directly from taskwarrior tasks time?

Thank you very much!

**Comment by coddingtonbear** [comment]
Oh, hrm; actually -- I'm afraid I haven't used timebook in a couple years now.  I very much doubt the `taskwarrior` command was useful for anybody but myself, so I'll just remove it from the readme for now.

**Comment by coddingtonbear** [comment]
If you _do_ intend to use `timebook` with `taskwarrior`, though, what I'd instead recommend doing is using `taskwarrior`'s Hook functionality.  Back when I wrote the hacky solution you happened upon, hooks did not yet exist!

**Comment by vonpupp** [comment]
Thank you @coddingtonbear. I installed the hook also, I thought they hook and timebook worked together.

My intention is to be able to export the time spent on the tasks as a ledger time log file. Any recommendation?
